# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-28 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_message', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_uuid', models.CharField(max_length=256, verbose_name='UUID')),
                ('message_content', models.TextField(verbose_name='CONTENTS')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
