# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 13:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('send_message', '0003_auto_20161028_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_details',
            name='number_of_arrival',
            field=models.CharField(default=0, max_length=32, verbose_name='Num. of Arrival'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message_details',
            name='number_of_devices',
            field=models.CharField(default=datetime.datetime(2016, 10, 30, 13, 40, 1, 852784, tzinfo=utc), max_length=32, verbose_name='Num. of Devices'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message_details',
            name='number_of_receivers',
            field=models.CharField(default=datetime.datetime(2016, 10, 30, 13, 40, 15, 171018, tzinfo=utc), max_length=32, verbose_name='Num. of Recervers'),
            preserve_default=False,
        ),
    ]
